
include: package:flutter_lints/flutter.yaml

linter:
  rules:
     avoid_print: true  # Uncomment to disable the `avoid_print` rule
     avoid_relative_lib_imports: true

     file_names: false    # lowercase_with_underscores
#     prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule


